name: Render Deployment

# on: release: types: [published] doens't wait ci-workflow

on: 
  workflow_run:
    workflows: ["Ci-workflow"]
    types: 
      - completed

jobs:
  Render-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Render deployment with tag
        if: ${{ startsWith(github.event.workflow_run.head_commit.ref, 'refs/tags/v') }}
        # context access might be invalid: ref ?
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: 
          echo "Triggering deployment at Render.com"
          curl "$deploy_url"